"""changed password length

Revision ID: 16eaf37e2edd
Revises: 607846e54cd4
Create Date: 2021-10-07 22:36:37.143894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16eaf37e2edd'
down_revision = '607846e54cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_login_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.create_unique_constraint('users_login_key', 'users', ['login'])
    # ### end Alembic commands ###
