"""Add password for user

Revision ID: 607846e54cd4
Revises: 82d253817c35
Create Date: 2021-10-02 21:45:04.593855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607846e54cd4'
down_revision = '82d253817c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'users', ['login'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.drop_column('users', 'login')
    # ### end Alembic commands ###
