"""remove index for login

Revision ID: a4f04ca851a7
Revises: 9aaeea24db45
Create Date: 2021-10-10 18:53:01.155802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f04ca851a7'
down_revision = '9aaeea24db45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_login', table_name='users')
    op.create_unique_constraint(None, 'users', ['login'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_login', 'users', ['login'], unique=False)
    # ### end Alembic commands ###
